
stages:
  - test

test-windows-amd64:
  stage: test
  tags:
    - msbuild
  script:
    - echo hello
    - npm i
    - echo so far so good
    - npm t
    - echo all done now

test-linux-386:
  stage: test
  tags:
    - docker-capsule-32
  script:
    - npm i --unsafe-perm
    - npm t

test-linux-amd64:
  stage: test
  tags:
    - docker-capsule-64
  script:
    - npm i --unsafe-perm
    - npm t

test-macos-amd64:
  stage: test
  tags:
    - darwin
  script:
    - npm i
    - npm t
