
stages:
  - test

test-windows-amd64:
  stage: test
  tags:
    - msbuild
  script:
    - npm i

test-linux-386:
  stage: test
  tags:
    - docker-capsule-32
  script:
    - npm i

test-macos-amd64:
  stage: test
  tags:
    - docker-capsule-64
  script:
    - npm i

test-macos-amd64:
  stage: test
  tags:
    - darwin
  script:
    - npm i
